baseurl: "/"
title: "Archetype"
init_js: "assets/js/init.js"
page_load_js: "assets/js/page_load.js"
params:
  landing_template: home
  palette: blue
  palettes:
    blue:
      sass:
        gradient1: "#27a1e3"
        gradient2: "#e7232a"
        accent1: "#5f9dd2"
        accent2: "#758ce1"
        accent3: "#e286a9"
    green:
      sass:
        gradient1: "#16f4cf"
        gradient2: "#6532e5"
        accent1: "#54d3cf"
        accent2: "#4f92d1"
        accent3: "#8075e5"
menus:
  main:
    - identifier: layouts
      title: Page Layouts
      url: "#"
      weight: 2
  layouts:
    - identifier: normal1
      title: Left Sidebar
      weight: 1
      url: "/left-sidebar"
    - identifier: normal2
      title: Right Sidebar
      weight: 2
      url: "/right-sidebar"
    - identifier: normal3
      title: No Sidebar
      weight: 3
      url: "/no-sidebar"
    - identifier: submenu
      title: Submenu
      weight: 4
      url: "#"
  submenu:
    - identifier: normal4
      title: Option One
      weight: 1
      url: "#"
    - identifier: normal5
      title: Option Two
      weight: 2
      url: "#"
    - identifier: normal6
      title: Option Three
      weight: 3
      url: "#"
    - identifier: normal7
      title: Option Four
      weight: 4
      url: "#"
  footer:
    - identifier: normal8
      title: Made with Stackbit
      weight: 4
      url: "https://www.stackbit.com"
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
templates:
  body_class: "{% if page.params.template == site.params.landing_template %}landing {% endif %}"
